service: tesseract-ocr-example-py38
frameworkVersion: ">=2.0.0"

plugins:
    - serverless-python-requirements

provider:
  name: aws
  region: us-west-2

custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile

layers:
  tesseractAl2:
    # specify path to layer content
    path: ./amazonlinux-2
    compatibleRuntimes:
      - python3.8

functions:
  tesseract-ocr:
    handler: handler.main
    runtime: python3.8
    layers:
      - { Ref: TesseractAl2LambdaLayer }
    events:
      - http:
          path: detect
          method: post