ACCEPTED_EXTENSIONS = [
    'image/png',
    'image/jpg',
    'image/jpeg',
]

ACCEPTED_PREPOSITIONS = [
    'the', 'of', 'la'
]

PROMOTION_CLASSES = [0, 1]
POTENTIAL_CLASS = 6
LEVEL_CLASS = 3
NAME_CLASS = 4
OPERATOR_CLASS = 5
FAVORITE_CLASS = 2


INPUT_WIDTH = 1600
INPUT_HEIGHT = 800

CONF_THRESHOLD = 0.4

NAME_MIN_CROP = 0.89
NAME_MAX_PAD = 0.005

LEVEL_MIN_CROP = 0.77
LEVEL_MAX_CROP = 0.93
LEVEL_WIDTH_CROP = 0.45

GRAY_THRESHOLD = 120
BRIGHTNESS_BUMP = 30